### ISSUE TITLE
layout: re-introduce focus jumping with arrow keys

### ISSUE THREAD

**Issue by arekkas** [ory-am/editor#255]
At the moment, `handleFocusPreviousHotKey` and `handleFocusNextHotKey` default to false and disable focus toggling. Although this useful for jumping between cells it had too many issues which is why it was disabled:

* [x] plugins/slate: selecting text and pressing arrow key causes focus to jump #253
* [x] layout/focus: when the first cell is selected, pressing up jumps around the first and the second cell #147
* [x] plugins/slate: slate stays focused although CELL_BLUR has been dispatched #135
* [x] plugin/slate: first click in slate is blurring it again #254

This issue boils down to slate / contenteditable troubles. It seems like slate is somewhat able to deal with focus/blur, but it has various bugs in all browsers. Additionally, for some reason, blurring is worse when slate is in the ORY Editor context.

**Comment by arekkas** [comment]
Switching focus between two slate instances in Firefox 49.0.2, with all DOM hacks disabled in the slate plugin and only `transform().focus().apply()` stuff:

![slate-focus-ff](https://cloud.githubusercontent.com/assets/3372410/20246118/92118418-a9b0-11e6-82fb-a579cbb9d164.gif)

This works much better in chrome though:

![slate-blur-chrome](https://cloud.githubusercontent.com/assets/3372410/20246125/bb8aa478-a9b0-11e6-8d73-7394fe3d63a1.gif)
